// Concrete subclass in the Template Method pattern
public class TextReport extends Report {

    public TextReport(String title, String summary, String content, String adminName) {
        super(title, summary, content, adminName);
    }

    @Override
    protected String formatHeader() {
        return "==================================================\n"
                + "  " + title + "\n"
                + "==================================================\n\n";
    }

    @Override
    protected String formatSummary() {
        return "SUMMARY:\n" + summary + "\n\n";
    }

    @Override
    protected String formatContent() {
        return "CONTENT:\n" + content + "\n\n";
    }

    @Override
    protected String formatFooter() {
        return "--------------------------------------------------\n"
                + "Generated by: " + adminName + "\n"
                + "Date: " + date + "\n";
    }

    @Override
    public String getFileExtension() {
        return ".txt";
    }
}
